services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: on-failure


volumes:
  pgdata: